/** @type {import('tailwindcss').Config} */
// Sistema de diseño migrado del prototipo intex / 迁移自 intex 原型的设计系统
export default {
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "primary-fixed-dim": "#4ae176",
        tertiary: "#4059aa",
        "on-tertiary-container": "#1e3a8a",
        "secondary-container": "#fea619",
        "secondary-fixed-dim": "#ffb95f",
        "inverse-primary": "#4ae176",
        "on-surface": "#0b1c30",
        primary: "#006e2f",
        "on-tertiary-fixed-variant": "#264191",
        "on-tertiary": "#ffffff",
        "surface-bright": "#f8f9ff",
        "on-primary-container": "#004b1e",
        "on-secondary-fixed": "#2a1700",
        "surface-tint": "#006e2f",
        "on-background": "#0b1c30",
        "tertiary-container": "#90a8ff",
        "surface-container-highest": "#d3e4fe",
        "surface-container-lowest": "#ffffff",
        "tertiary-fixed": "#dce1ff",
        error: "#ba1a1a",
        outline: "#6d7b6c",
        secondary: "#855300",
        "secondary-fixed": "#ffddb8",
        "primary-container": "#22c55e",
        "on-tertiary-fixed": "#00164e",
        "inverse-on-surface": "#eaf1ff",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#002109",
        "on-error-container": "#93000a",
        "on-secondary": "#ffffff",
        "surface-container": "#e5eeff",
        "primary-fixed": "#6bff8f",
        "surface-variant": "#d3e4fe",
        background: "#f8f9ff",
        "on-surface-variant": "#3d4a3d",
        "surface-container-high": "#dce9ff",
        surface: "#f8f9ff",
        "inverse-surface": "#213145",
        "on-secondary-container": "#684000",
        "on-primary": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-dim": "#cbdbf5",
        "outline-variant": "#bccbb9",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#005321",
        "on-secondary-fixed-variant": "#653e00",
        "tertiary-fixed-dim": "#b6c4ff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "40px",
        "margin-desktop": "32px",
        "margin-mobile": "16px",
        lg: "24px",
        sm: "8px",
        md: "16px",
        xs: "4px",
        base: "4px",
        "2xl": "64px",
        gutter: "24px",
      },
      fontFamily: {
        "headline-lg": ["Hanken Grotesk"],
        "body-md": ["Inter"],
        "label-md": ["Inter"],
        "body-lg": ["Inter"],
        "headline-lg-mobile": ["Hanken Grotesk"],
        "headline-md": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "label-sm": ["Inter"],
      },
      fontSize: {
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.03em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
